### ISSUE TITLE
Fail to execute the snack project program

### ISSUE THREAD

**Issue by givenchyhuang** [HSAFoundation/HSA-Docs-AMD#2]
I build the hsa docker.
When I login the docker , I follow the HSA Software Install Instructions to install Runtime , CLOC , Driver and HSAIL Compiler.
Each step is succeed.
(Install HSA Runtime -> Install HSA Linux Kernel Drivers and Reboot -> Install HSAIL Compiler -> Install and test cloc)
But when I use the CLOC to compile the snack or hsa project , the error is happened.

Could not create BRIG module: 3
The ELF file is invalid or possibley corrupted.
Creating the brig module from vector_copy.brig failed

How can I use opencl 2.0 in hsa docker ? 
Thanks.
Regards.,

**Comment by jedwards-AMD** [comment]
First, OpenCL is not implemented on top of HSA at this time. You can develop HSA related programs by directly using the HSA API's provided in the HSA runtime. CLOC translates kernels written in OpenCL C into HSAIL, which can then be loaded, finalized and executed using the HSA runtime, not the OpenCL runtime.

Please look at the sample provided at https://github.com/HSAFoundation/HSA-Runtime-AMD/tree/master/sample for an example of a pure HSA application. The sample includes code for loading and finalizing a HSAIL kernel from an ELF container (vector_copy.brig in the RUNTIME sample in this case).

Is it possible for you to provide the Docker container that is exhibiting the error?

**Comment by boyihuang** [comment]
Thanks for your answer .
I could successfully run a sample code on AMD kaveri.
But what I want to ask is how to run a hsa application in the "hsa docker" ?
How to set up opencl environment in docker to run opencl 2.0 using cloc or other methods?
 
Because when I login the hsa docker , I follow the HSA Software Install Instructions to install Runtime , CLOC , Driver and HSAIL Compiler in hsa docker .
Each step is succeed.
(Install HSA Runtime -> Install HSA Linux Kernel Drivers and Reboot -> Install HSAIL Compiler -> Install and test cloc)
But when I use the CLOC to compile the snack or hsa project , the error is happened.
Error messages is as shown : 
Could not create BRIG module: 3
The ELF file is invalid or possibley corrupted.
Creating the brig module from vector_copy.brig failed

So I want to know how to run a hsa program in hsa docker .

Thanks : )

**Comment by jedwards-AMD** [comment]
What version of the docker image are you using? The ubuntu-hsa-v1.0-dev image is pre-configured to run CLOC (CLOC, compiler and runtime installations NOT required), and I was able to build both hsa and snack CLOC samples using this image. The way I start the container is to use the following command:
.
'sudo docker run --device /dev/kfd -v <host dir>:/mnt -i -t jedwards/ubuntu-hsa-v1.0-dev /bin/bash'
.
The <host dir> contains the CLOC github repository which was downloaded to the docker hosts filesystem. For information about available HSA docker containers consult this link: https://github.com/HSAFoundation/HSA-Docs-AMD/wiki/HSA-Docker-Containers:---Downloading-and-Running-HSA-on-Docker

**Comment by givenchyhuang** [comment]
I could run the docker and run the program according to the command.
I have a the other one question is when I run a program in docker ,does it run as fast as in host machine or more slower ?
I think the hsa program in docker will use the host gpu resource , does it ?

Thanks : )

**Comment by jedwards-AMD** [comment]
Docker isn't virtualization, as such -- instead, it's an abstraction on top of the kernel's support for different process namespaces, device namespaces, etc.; one namespace isn't inherently more expensive or inefficient than another, so what actually makes Docker have a performance impact is a matter of what's actually in those namespaces. If the software is equivalent in the docker container to the software on the host, performance should be similar.

Any other Docker related questions should be directed to a official Docker support page like https://www.digitalocean.com/community/questions.
